export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const ITEM_QUANTITY = "ITEM_QUANTITY";
export const INCREASE_CART_QUANTITY = "INCREASE_CART_QUANTITY";
export const CLOSE_CART = "CLOSE_CART";
export const OPEN_CART = "OPEN_CART";
export const PROCESS_CHECKOUT = "PROCESS_CHECKOUT";
